WDP240901-9
matwjablonski/kodilla-wdp-2409-01 pull request #10
Opened 2024-09-22 01:43 UTC by dave8git

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-9

2024-09-22 12:50 UTC, patrykbn approved these changes
Seems good to me

2024-09-22 14:14 UTC, dave8git commented
> Seems good to me

Thanks! :)

2024-09-23 08:39 UTC, matwjablonski commented on src/styles/settings.scss
> +    background-color $bg-transition-time, color $text-transition-time,
indentation and in the end of lines should be `;`

2024-09-23 10:37 UTC, dave8git commented on src/styles/settings.scss
> +    background-color $bg-transition-time, color $text-transition-time,
Identation fixed. 
Line ends fixed from , to ;

2024-09-23 10:39 UTC, matwjablonski requested changes

2024-09-23 10:39 UTC, matwjablonski commented on src/styles/settings.scss
> +
why so many empty lines?

2024-09-23 10:48 UTC, dave8git commented on src/styles/settings.scss
> +
Fixed empty lines.

2024-09-24 17:30 UTC, patrykbn submitted a review, later dismissed

2024-09-25 13:29 UTC, matwjablonski approved these changes

2024-09-25 13:29 UTC, merged