WDP240901-10
matwjablonski/kodilla-wdp-2409-01 pull request #11
Opened 2024-09-22 14:02 UTC by dave8git

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-10

2024-09-23 08:40 UTC, matwjablonski requested changes

2024-09-23 08:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +  console.log('categories', categories);
console.log to remove

2024-09-23 08:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +                  <a href="#">{category.name}</a>
why anchor instead of Link?

2024-09-23 08:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +            // color: white;
if empty it should be removed

2024-09-23 11:06 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.js
> +  console.log('categories', categories);
removed.

2024-09-23 11:07 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.js
> +                  <a href="#">{category.name}</a>
changed to Link

2024-09-23 11:07 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +            // color: white;
removed.

2024-09-24 15:19 UTC, patrykbn requested changes
Just 1 issue I found. For screen width >1200px the text gets wraped like in the screenshot below.
![image](https://github.com/user-attachments/assets/b9a30ae4-9dd5-4762-b32b-7a82e0543a53)

2024-09-24 15:31 UTC, matwjablonski commented
this can be fixed by css rule `white-space: nowrap`

2024-09-24 17:05 UTC, dave8git commented
> Just 1 issue I found. For screen width >1200px the text gets wraped like in the screenshot below. ![image](https://private-user-images.githubusercontent.com/165287438/370350797-b9a30ae4-9dd5-4762-b32b-7a82e0543a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTc3OTcsIm5iZiI6MTcyNzE5NzQ5NywicGF0aCI6Ii8xNjUyODc0MzgvMzcwMzUwNzk3LWI5YTMwYWU0LTlkZDUtNDc2Mi1iMzJiLTdhODJlMDU0M2E1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxNzA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmFhNTU0NDRlMTM3ZDA0NDNhM2UyMmJmN2E1ODU4MWE0N2M1YzIwMDYwY2JlMWZiMmEwMmU4YWE2ZjQxNjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sKC3NlBwSmhJJVK7CdGkjOu4AmqjKTaaqv0xSOcCYSw)

RWD was not part of this task

2024-09-24 17:06 UTC, dave8git commented
> > Just 1 issue I found. For screen width >1200px the text gets wraped like in the screenshot below. ![image](https://private-user-images.githubusercontent.com/165287438/370350797-b9a30ae4-9dd5-4762-b32b-7a82e0543a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTc3OTcsIm5iZiI6MTcyNzE5NzQ5NywicGF0aCI6Ii8xNjUyODc0MzgvMzcwMzUwNzk3LWI5YTMwYWU0LTlkZDUtNDc2Mi1iMzJiLTdhODJlMDU0M2E1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxNzA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmFhNTU0NDRlMTM3ZDA0NDNhM2UyMmJmN2E1ODU4MWE0N2M1YzIwMDYwY2JlMWZiMmEwMmU4YWE2ZjQxNjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sKC3NlBwSmhJJVK7CdGkjOu4AmqjKTaaqv0xSOcCYSw)
> 

RWD is not part of this task.

2024-09-24 17:15 UTC, patrykbn reviewed
@matwjablonski  Can you please take a look and guide us with the steps we should take in this situation?

2024-09-24 17:15 UTC, patrykbn commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +          text-decoration: none;
add: 
font-size: 14px;

explained in comment to whole ProductSearch,module.scss file

2024-09-24 17:15 UTC, patrykbn commented on src/components/features/ProductSearch/ProductSearch.module.scss
I would propose to get rid of all the white-space: nowrap; styles to avoide problems with future RWD implementations.

My proposition is to add font size as commented on line 29, as it is part of a different task and solves the problem for now.

@matwjablonski Would you agree or can we leave the white-space styles?

2024-09-25 10:10 UTC, dave8git reviewed
I applied requested changes.

2024-09-25 10:10 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.module.scss
I did as you requested. If there will be problems with RWD in the future one of us will add no-wrap. Please there is not time for further discusssion of this minor issue.

2024-09-25 10:10 UTC, dave8git commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +          text-decoration: none;
Did as you recommended.

2024-09-25 15:41 UTC, patrykbn requested changes

2024-09-25 15:41 UTC, patrykbn commented on src/components/features/ProductSearch/ProductSearch.js
> +              <a href="#">Select a category</a>
category div used to look like this:
![image](https://github.com/user-attachments/assets/2969bcf1-18a8-4310-8d99-c772d7dcfbd5)

and like this with hover effect:
![image](https://github.com/user-attachments/assets/0eb4a95c-b8df-4e6a-ad9a-c24802c052df)


Now it looks like this:
![image](https://github.com/user-attachments/assets/c9393794-93af-4fb1-83b4-f3d4bbeb1a9b)

Seems to me like:
-Icon color is missing
-hover effect is gone
-margins are a little off compared to original look

2024-09-26 21:32 UTC, patrykbn approved these changes

2024-09-27 16:30 UTC, matwjablonski approved these changes

2024-09-27 16:30 UTC, merged