Added ProductBox hover effect
matwjablonski/kodilla-wdp-2409-01 pull request #12
Opened 2024-09-22 14:08 UTC by patrykbn

Hid the quick view and add to cart buttons to only be shown when hovering over the productBox.
Price box also included in productBox hover effect.

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-4

2024-09-22 14:19 UTC, dave8git submitted a review, later dismissed
ok

2024-09-23 08:44 UTC, matwjablonski requested changes

2024-09-23 08:44 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +      background-color: #ffffff;
color should be from taken variable

2024-09-23 08:44 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +        background-color: #ffffff !important;
please try to avoid !important

2024-09-23 08:44 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    background-color: #292929 !important;
as above

2024-09-23 17:28 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +      background-color: #ffffff;
replaced with variable from settings.scss

2024-09-23 17:28 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +        background-color: #ffffff !important;
Edited styles after merge and deleted !important

2024-09-23 20:14 UTC, dave8git approved these changes

2024-09-23 21:36 UTC, matwjablonski commented
conflicts

2024-09-24 15:13 UTC, matwjablonski commented
conflicts

2024-09-25 15:29 UTC, dave8git submitted a review, later dismissed

2024-09-25 18:51 UTC, dave8git submitted a review, later dismissed

2024-09-26 15:56 UTC, matwjablonski commented
conflicts

2024-09-27 16:35 UTC, matwjablonski approved these changes

2024-09-27 16:35 UTC, merged