WDP240901-14
matwjablonski/kodilla-wdp-2409-01 pull request #13
Opened 2024-09-22 20:43 UTC by patrykbn

Added RWD for tablets and mobile devices.
Added dropdown menu for mobile devices

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-14

2024-09-23 08:45 UTC, matwjablonski requested changes

2024-09-23 08:45 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +    background-color: #ffffff;
color from variables

2024-09-23 08:45 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
color from variables

2024-09-23 17:49 UTC, patrykbn commented on src/components/layout/MenuBar/MenuBar.module.scss
> +    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
color variables added

2024-09-23 17:49 UTC, patrykbn commented on src/components/layout/MenuBar/MenuBar.module.scss
> +    background-color: #ffffff;
color variables added

2024-09-24 07:28 UTC, dave8git commented
I think task mentioned that on small screens dropdown menu should hide, and only after clicking on an icon, dropdown menu should appear and cover part of the page: 
![Screenshot 2024-09-24 092730](https://github.com/user-attachments/assets/2cf9fa8b-8893-435e-9eee-8689b12b85fe)
Please hide dropdown menu for smaller screen sizes.

2024-09-24 17:19 UTC, dave8git commented
> > I think task mentioned that on small screens dropdown menu should hide, and only after clicking on an icon, dropdown menu should appear and cover part of the page: ![Screenshot 2024-09-24 092730](https://private-user-images.githubusercontent.com/47623358/370178444-2cf9fa8b-8893-435e-9eee-8689b12b85fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTMyNDYsIm5iZiI6MTcyNzE5Mjk0NiwicGF0aCI6Ii80NzYyMzM1OC8zNzAxNzg0NDQtMmNmOWZhOGItODg5My00MzVlLTllZWUtODY4OWIxMmI4NWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE1NDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmM4NDE0NWQzYWViZDBlYThiMWJhZDFkOThjZmUzZWQ2ZDcwZjJiZTBlNzZkZGQ3YzYzZTU2Y2MyMDMxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t_uRE1_CvxaiZPt5nIVgOnNjpobBTAhc5gH6EV8xllw) Please hide dropdown menu for smaller screen sizes.
> 
> The task was for the search bar to be under the Menu buttons for tablets, and for mobile devices the menu to change to a clickable dropdown menu on the right of the searchbar. I don't see a reason to hide the dropdown menu for mobile devices. How would users access the menu options?

What would be the reason to have two category dropdowns then? It's redundant. Why would you have one in select category and another one in dropdown menu that shows when click the icon? It should be visible on small screens, that's why you shouldn't have large box just icon and then menu that hides part of the screen when it's open.

2024-09-24 19:53 UTC, patrykbn commented
> > > I think task mentioned that on small screens dropdown menu should hide, and only after clicking on an icon, dropdown menu should appear and cover part of the page: ![Screenshot 2024-09-24 092730](https://private-user-images.githubusercontent.com/47623358/370178444-2cf9fa8b-8893-435e-9eee-8689b12b85fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTMyNDYsIm5iZiI6MTcyNzE5Mjk0NiwicGF0aCI6Ii80NzYyMzM1OC8zNzAxNzg0NDQtMmNmOWZhOGItODg5My00MzVlLTllZWUtODY4OWIxMmI4NWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE1NDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmM4NDE0NWQzYWViZDBlYThiMWJhZDFkOThjZmUzZWQ2ZDcwZjJiZTBlNzZkZGQ3YzYzZTU2Y2MyMDMxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t_uRE1_CvxaiZPt5nIVgOnNjpobBTAhc5gH6EV8xllw) Please hide dropdown menu for smaller screen sizes.
> > 
> > 
> > The task was for the search bar to be under the Menu buttons for tablets, and for mobile devices the menu to change to a clickable dropdown menu on the right of the searchbar. I don't see a reason to hide the dropdown menu for mobile devices. How would users access the menu options?
> 
> What would be the reason to have two category dropdowns then? It's redundant. Why would you have one in select category and another one in dropdown menu that shows when the user clicks on the icon? It should be visible on small screens, that's why you shouldn't have large box just icon and then menu that hides part of the screen when it's open. You should hide large category dropdown menu, and show only the icons, if someone wants to see categories they will click on the icon and menu will come down.
> 
> "Na tabletach wyszukiwanie ma być pod menu, a na mniejszych ekranach ma być wyszukiwanie **i obok niego ikona** mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony."

Dawidzie, napiszę Ci po polsku, żeby nie było żadnych wątpliwości,
Zauważ, że select a category i dropdown menu to dwa kompletnie inne elementy.
Do dropdown menu "chowają się" przyciski menu które są widoczne dla większych ekranów. (tj. HOME FURNITURE CHAIR TABLE SOFA BEDROOM BLOG)
Select a category z kolei dotyczy kategorii w której chcemy wyszukać produkt- nie podstrony z MENU. Tutaj po rozwinięciu select a category otrzymasz kategorie BED CHAIR SOFA TABLE DINING. Teraz tego nie widać, ale w zadaniu, które sam z resztą robiłeś kategorie są widoczne po najechaniu na element.

Prosiłbym Cie na przyszłość, żeby czytać zadania dokładnie i przemyślenie treści, bo oboje tracimy na takie wyjaśnianie cenny czas.

2024-09-24 20:28 UTC, dave8git commented
> > > > I think task mentioned that on small screens dropdown menu should hide, and only after clicking on an icon, dropdown menu should appear and cover part of the page: ![Screenshot 2024-09-24 092730](https://private-user-images.githubusercontent.com/47623358/370178444-2cf9fa8b-8893-435e-9eee-8689b12b85fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTMyNDYsIm5iZiI6MTcyNzE5Mjk0NiwicGF0aCI6Ii80NzYyMzM1OC8zNzAxNzg0NDQtMmNmOWZhOGItODg5My00MzVlLTllZWUtODY4OWIxMmI4NWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE1NDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmM4NDE0NWQzYWViZDBlYThiMWJhZDFkOThjZmUzZWQ2ZDcwZjJiZTBlNzZkZGQ3YzYzZTU2Y2MyMDMxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t_uRE1_CvxaiZPt5nIVgOnNjpobBTAhc5gH6EV8xllw) Please hide dropdown menu for smaller screen sizes.
> > > 
> > > 
> > > The task was for the search bar to be under the Menu buttons for tablets, and for mobile devices the menu to change to a clickable dropdown menu on the right of the searchbar. I don't see a reason to hide the dropdown menu for mobile devices. How would users access the menu options?
> > 
> > 
> > What would be the reason to have two category dropdowns then? It's redundant. Why would you have one in select category and another one in dropdown menu that shows when the user clicks on the icon? It should be visible on small screens, that's why you shouldn't have large box just icon and then menu that hides part of the screen when it's open. You should hide large category dropdown menu, and show only the icons, if someone wants to see categories they will click on the icon and menu will come down.
> > "Na tabletach wyszukiwanie ma być pod menu, a na mniejszych ekranach ma być wyszukiwanie **i obok niego ikona** mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony."
> 
> Dawidzie, napiszę Ci po polsku, żeby nie było żadnych wątpliwości, Zauważ, że select a category i dropdown menu to dwa kompletnie inne elementy. Do dropdown menu "chowają się" przyciski menu które są widoczne dla większych ekranów. (tj. HOME FURNITURE CHAIR TABLE SOFA BEDROOM BLOG) Select a category z kolei dotyczy kategorii w której chcemy wyszukać produkt- nie podstrony z MENU. Tutaj po rozwinięciu select a category otrzymasz kategorie BED CHAIR SOFA TABLE DINING. Teraz tego nie widać, ale w zadaniu, które sam z resztą robiłeś kategorie są widoczne po najechaniu na element.
> 
> Prosiłbym Cie na przyszłość, żeby czytać zadania dokładnie i przemyślenie treści, bo oboje tracimy na takie wyjaśnianie cenny czas.

Patryku, masz rację. Przyjrzałem się treści i to co mówisz jest prawdą. Na pierwszy rzut oka patrzyłem na zachowanie RWD i nie pasuje mi to, że przez dwa okna wyszukiwania (select-dropdown, i input-search) na mobilkach rozjeżdża się widok. Popatrz sam jak to wygląda na Iphone XR: 

![image](https://github.com/user-attachments/assets/5ebaa303-c294-4fe0-b8f4-093935e6de6e)

2024-09-25 18:55 UTC, dave8git approved these changes

2024-09-25 19:01 UTC, dave8git commented
> @dave8git I edited the styles to look good on viewports of a minimum of about 410px width. Let me know if you think it looks good now. Thank you!

I wonder if this line doesn't suggest that search box should be under the menu. On year design, they are side by side. I think one should be below?  Do you agree? I see two steps here. 1. On tablets searchbox should be below menu, and 2. on mobile, there should be only search box and  icon which will open dropdown covering portion of the page. "Na tabletach *1.* wyszukiwanie ma być pod menu, "2.* a na mniejszych ekranach ma być wyszukiwanie i obok niego ikona mobilnego menu, które po rozwinięciu ma pokazywać dropdown przykrywający treść strony."

2024-09-25 19:49 UTC, dave8git approved these changes

2024-09-26 15:56 UTC, matwjablonski commented
conflicts

2024-09-28 17:45 UTC, dave8git approved these changes

2024-09-30 07:27 UTC, matwjablonski approved these changes

2024-09-30 07:27 UTC, merged