WDP240901-16
matwjablonski/kodilla-wdp-2409-01 pull request #14
Opened 2024-09-24 12:42 UTC by dave8git

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-16

2024-09-25 15:45 UTC, patrykbn requested changes
Just a few white-spaces need to be deleted to clean up code

2024-09-25 15:45 UTC, patrykbn commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +import React from 'react';
white space after ;

2024-09-25 15:45 UTC, patrykbn commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +import FeatureBox from '../../common/FeatureBox/FeatureBox';
white-space after ;

2024-09-25 15:45 UTC, patrykbn commented on src/components/features/FeatureBoxes/FeatureBoxes.module.scss
> +
delete empty lines

2024-09-25 16:25 UTC, patrykbn submitted a review, later dismissed

2024-09-25 17:42 UTC, matwjablonski requested changes

2024-09-25 17:42 UTC, matwjablonski commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +import React from 'react';
you didn't remove that white space

2024-09-25 17:42 UTC, matwjablonski commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +import FeatureBox from '../../common/FeatureBox/FeatureBox';
same

2024-09-25 17:42 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +  @media (max-width: 490px) {
before @media query add one empty line

2024-09-25 19:11 UTC, dave8git commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +import React from 'react';
white space removed.

2024-09-25 19:11 UTC, dave8git commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +import FeatureBox from '../../common/FeatureBox/FeatureBox';
white space removed.

2024-09-25 19:15 UTC, patrykbn approved these changes

2024-09-26 15:57 UTC, matwjablonski approved these changes

2024-09-26 15:58 UTC, merged