WDP240901-13
matwjablonski/kodilla-wdp-2409-01 pull request #21
Opened 2024-09-27 09:27 UTC by dave8git

https://projects.kodilla.com/browse/WDP240901-13

2024-09-27 13:03 UTC, patrykbn requested changes

2024-09-27 13:03 UTC, patrykbn commented on src/components/features/NewFurniture/NewFurniture.js
> +      // console.log('rightAction');
remove console.log

2024-09-27 13:03 UTC, patrykbn commented on src/components/features/NewFurniture/NewFurniture.js
> +    // return the object with new state when props changed
remove comment

2024-09-27 13:03 UTC, patrykbn commented on src/components/features/NewFurniture/NewFurniture.js
> +      // console.log('leftAction');
remove console.log

2024-09-27 13:11 UTC, dave8git commented on src/components/features/NewFurniture/NewFurniture.js
> +      // console.log('rightAction');
console.log() usunięte.

2024-09-27 13:11 UTC, dave8git commented on src/components/features/NewFurniture/NewFurniture.js
> +      // console.log('leftAction');
removed.

2024-09-27 13:11 UTC, dave8git commented on src/components/features/NewFurniture/NewFurniture.js
> +    // return the object with new state when props changed
comment removed

2024-09-27 13:13 UTC, patrykbn submitted a review, later dismissed

2024-09-28 23:54 UTC, patrykbn approved these changes

2024-09-30 08:09 UTC, matwjablonski approved these changes

2024-09-30 08:09 UTC, merged