WDP240901-21
matwjablonski/kodilla-wdp-2409-01 pull request #26
Opened 2024-10-03 16:53 UTC by patrykbn

https://projects.kodilla.com/browse/WDP240901-21

Added StarReview component with functionality, redux and addition to initialstate for current user reviews

Replaced stars in productbox and hotdeals with StarReview components.

2024-10-03 17:23 UTC, dave8git submitted a review, later dismissed

2024-10-04 11:16 UTC, matwjablonski requested changes

2024-10-04 11:16 UTC, matwjablonski commented on src/components/common/StarReview/StarReview.js
> +  const existingReview = useSelector(state => {
you can omit return here, just using `state => getReviewById(state, id)`

2024-10-04 11:16 UTC, matwjablonski commented on src/components/common/StarReview/StarReview.js
> +      } else {
too many nested if statements.

instead try to use negation to keep it cleaner

2024-10-04 17:21 UTC, patrykbn commented on src/components/common/StarReview/StarReview.js
> +  const existingReview = useSelector(state => {
fixed

2024-10-04 17:21 UTC, patrykbn commented on src/components/common/StarReview/StarReview.js
> +      } else {
used negetion and got rid of nested if

2024-10-04 19:19 UTC, dave8git approved these changes

2024-10-07 21:09 UTC, matwjablonski approved these changes

2024-10-07 21:09 UTC, merged