Wdp240901 1
matwjablonski/kodilla-wdp-2409-01 pull request #3
Opened 2024-09-20 13:26 UTC by dave8git

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-1

2024-09-20 15:42 UTC, patrykbn reviewed
Delete a few blank spaces to keep the code clean
Take a look at the .buttons style

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.js
> +
Unnecessary blank space

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +
Unnecessary blank space

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +
Unnecessary blank space

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +
Unnecessary blank space

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +
Unnecessary blank space

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +
Unnecessary blank space

2024-09-20 15:42 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .buttons {
Original .buttons styles were inside .photo
perhaps add it back into .photo to avoid future conflicts?

2024-09-20 15:45 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .buttons {
This is by design. I removed them, otherwise they were being coverd by photos. I also added some extra styles, so the fit underneath the photos and have enough space for some responsivness.

2024-09-21 20:51 UTC, matwjablonski requested changes

2024-09-21 20:51 UTC, matwjablonski commented on src/redux/initialState.js
> +
this empty line is redundant

2024-09-21 20:51 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    background-image: url('/public/images/productBox/');
this rule is unnecessary, basically it's doing nothing

2024-09-21 20:51 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    padding: 0 10px 0 10px;
you can simplify it even more:
```css
padding: 0 10px;

2024-09-21 21:50 UTC, patrykbn approved these changes

2024-09-23 12:43 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.module.scss
> +
removed

2024-09-23 12:43 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.module.scss
> +
removed

2024-09-23 12:50 UTC, dave8git commented on src/redux/initialState.js
> +
removed empty line.

2024-09-23 12:52 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.module.scss
> +    background-image: url('/public/images/productBox/');
removed

2024-09-24 14:36 UTC, patrykbn approved these changes
Everything looks good after the changes

2024-09-24 15:10 UTC, matwjablonski approved these changes

2024-09-24 15:10 UTC, merged