WDP240901-2
matwjablonski/kodilla-wdp-2409-01 pull request #4
Opened 2024-09-20 15:14 UTC by dave8git

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-2

2024-09-21 06:07 UTC, patrykbn requested changes

2024-09-21 06:07 UTC, patrykbn commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +  const cartCounterClass = cartCount > 9 ? `${styles.cartCounter} ${styles.large}` : styles.cartCounter;
I think this should be (...) cartCount < 9 ? (...) 
Intuitively, I would say if the number has more than 1 digit, the font should get a little smaller, if at all.
WDP240901-2 additionally states the max digits should be 5, so the max number is to be 99999. There is no code controlling that.
I would have the .cartBox be wider depending on the amount of digits in cartCount so that the number does not overlap on the cart icon. When cartCount is 99999 the cart icon is almost entirely hidden.

2024-09-21 06:07 UTC, patrykbn commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        &.large {
I would change the styles according to the comment in CompanyClaim.js

2024-09-21 06:07 UTC, patrykbn commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +    <div className={styles.root}>
indentations of divs seem to be a little off

2024-09-21 18:55 UTC, dave8git commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        &.large {
Which comment?

2024-09-21 19:20 UTC, dave8git commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +    <div className={styles.root}>
divs indentation fixed.

2024-09-21 19:21 UTC, dave8git commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        &.large {
Ok, coment on top.

2024-09-21 19:23 UTC, dave8git commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +  const cartCounterClass = cartCount > 9 ? `${styles.cartCounter} ${styles.large}` : styles.cartCounter;
ad. 1. Double digit numbers start at 10 so cartCount < 9 must stay. 
ad. 2. This is a design decision. I can't say i understand this comment 100%. 
ad. 3. Code for trimming more then 5 digits added. 
ad. 4. This is a RWD issue, we would need separate task for fixing RWD design on cart, maybe in the future task?

2024-09-21 21:01 UTC, matwjablonski requested changes

2024-09-21 21:01 UTC, matwjablonski commented on src/redux/initialState.js
> +      favorite: true,
it's not part of this task.

2024-09-24 07:15 UTC, dave8git commented on src/redux/initialState.js
> +      favorite: true,
deleted code from other tasks

2024-09-24 07:16 UTC, dave8git commented on src/components/layout/CompanyClaim/CompanyClaim.js
> +              <div className={cartCounterClass}>{cartCount.toString().slice(0, 5)}</div>
deleted code and added error handling (every time cartCount value changes and when component restarts)

2024-09-24 15:05 UTC, patrykbn requested changes
In my opinion, the cartBox still does not work as it should

2024-09-24 15:05 UTC, patrykbn commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        &.large {
I think this still does not look right.
If We have 99999 item in basket the element looks like this:
![image](https://github.com/user-attachments/assets/ffec9d8e-2e01-4b17-a6fe-a4464ec16ec2)
cartBox should be wider in this situation

2024-09-24 15:06 UTC, patrykbn commented on src/redux/productsRedux.js
> +/* action creators */
This is about the actions below line 8

2024-09-24 21:34 UTC, dave8git commented on src/redux/productsRedux.js
> +/* action creators */
I needed code from this task in other tasks, and vice versa. All functionality for the task WDP240901-2 works ok.

2024-09-24 21:35 UTC, dave8git commented on src/redux/initialState.js
> +      favorite: false,
Yes that's correct, i worked on this task with code merged from other tasks. I had to work this way since other tasks were not merged into main still.

2024-09-24 21:36 UTC, dave8git commented on src/redux/initialState.js
> -      prevPrice: 40,
also code after task merging.

2024-09-25 15:24 UTC, patrykbn approved these changes

2024-09-25 17:38 UTC, matwjablonski approved these changes

2024-09-25 17:38 UTC, merged