Converted FeatureBox to a link and added hover effect
matwjablonski/kodilla-wdp-2409-01 pull request #5
Opened 2024-09-20 15:15 UTC by patrykbn

FeatureBox.js:
Converted content of FeatureBox to be a clickable link. Link temporarily disabled so that is does not navigate to a different page.
Additionaly added a PropType to check the content of link and require a string.

FeatureBox.module.scss:
added styles for added link with !important to overwrite default underline on hover
added transition time and style for hover effect to: .root .iconWrapper and .content
added hover effect styles to match active state for the FeatureBox
deleted empty style for p that was causing a warning

FeatureBoxes.js:
added link prop. to FeatureBox with a placeholder for future implementation

2024-09-20 15:22 UTC, dave8git submitted a review, later dismissed

2024-09-21 21:03 UTC, matwjablonski requested changes

2024-09-21 21:03 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.js
> +    <a
it should not be an anchor element, it should be Link component from react-router library

2024-09-21 21:03 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +      color: #ffffff;
this color should be taken from variables

2024-09-21 21:20 UTC, patrykbn commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +      color: #ffffff;
This was done before the variables were added, but its true. I'll change it

2024-09-22 00:52 UTC, dave8git submitted a review, later dismissed

2024-09-23 08:26 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +      color: #ffffff;
colors are merged to main branch :) now you can align this part ;)

2024-09-23 20:13 UTC, dave8git approved these changes

2024-09-23 21:32 UTC, matwjablonski approved these changes

2024-09-23 21:32 UTC, merged