Add background color for compare and favorite
matwjablonski/kodilla-wdp-2409-01 pull request #7
Opened 2024-09-21 21:55 UTC by dave8git

2024-09-22 12:08 UTC, patrykbn approved these changes

2024-09-22 12:08 UTC, patrykbn approved these changes
Everything looks good to me

2024-09-23 08:31 UTC, matwjablonski requested changes

2024-09-23 08:31 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +    {console.log('compare', compare)}
remove console log

2024-09-23 08:31 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          className={favorite ? styles.activeColor : undefined }
```js
favorite && styles.activeColor
```

2024-09-23 08:31 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          className={compare ? styles.activeColor : undefined }
as above

2024-09-23 08:31 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .activeColor {
maybe name could be just `active` and it should be understandable

2024-09-23 12:28 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.js
> +    {console.log('compare', compare)}
console.log removed.

2024-09-23 12:29 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.js
> +          className={compare ? styles.activeColor : undefined }
Fixed logice.

2024-09-23 12:29 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .activeColor {
Changed according to recomendation.

2024-09-24 21:51 UTC, dave8git commented on src/redux/initialState.js
> +      compare: false,
fixed

2024-09-24 21:52 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.js
> +const ProductBox = ({ name, price, promo, stars, backgroundPhoto, compare, favorite, prevPrice }) => (
proptypes added.

2024-09-24 22:02 UTC, dave8git commented on src/redux/initialState.js
> +      newFurniture: false,
deleted unnecessary line.

2024-09-25 13:27 UTC, matwjablonski approved these changes

2024-09-25 13:27 UTC, merged