WDP240901-11
matwjablonski/kodilla-wdp-2409-01 pull request #8
Opened 2024-09-21 22:37 UTC by dave8git

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=239&projectKey=WDP240901&view=detail&selectedIssue=WDP240901-11

2024-09-23 08:34 UTC, matwjablonski approved these changes

2024-09-23 16:37 UTC, patrykbn requested changes

2024-09-23 16:37 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.js
>  ProductBox.propTypes = {
I think we need to add PropType for prevPrice
prevPrice: PropTypes.number,

2024-09-23 17:25 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.js
>  ProductBox.propTypes = {
Proptype added, thanks for pointing this out.

2024-09-24 15:09 UTC, patrykbn submitted a review, later dismissed

2024-09-24 15:12 UTC, matwjablonski commented
conflicts

2024-09-24 16:47 UTC, patrykbn requested changes

2024-09-24 16:47 UTC, patrykbn commented on src/redux/initialState.js
> +      newFurniture: false,
delete line 79

2024-09-24 16:47 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.js
>  ProductBox.propTypes = {
Should we add propType for favorite?

2024-09-24 16:57 UTC, dave8git commented on src/redux/initialState.js
> +      newFurniture: false,
Because there was no merge for other tasks, i had to pull some code from other tasks, that's why i want to leave it here.

2024-09-24 16:59 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.js
>  ProductBox.propTypes = {
Thanks added.

2024-09-24 17:22 UTC, patrykbn requested changes

2024-09-24 17:22 UTC, patrykbn commented on src/components/common/ProductBox/ProductBox.js
> +  favorite: PropTypes.string,
favorite is true or false.
I think this should be 
favorite: PropTypes.bool

2024-09-25 08:36 UTC, dave8git commented on src/components/common/ProductBox/ProductBox.js
> +  favorite: PropTypes.string,
Dzięki, poprawiłem.

2024-09-25 13:28 UTC, matwjablonski commented
conflicts

2024-09-25 15:28 UTC, patrykbn approved these changes

2024-09-26 15:53 UTC, matwjablonski approved these changes

2024-09-26 15:54 UTC, merged